apiVersion: apps/v1
kind: Deployment
metadata:
  name: qr-generator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: qr-generator
  template:
    metadata:
      labels:
        app: qr-generator
    spec:
      containers:
      - name: qr-generator
        image: rhxpchispi/qr-generator:1.0
        ports:
        - containerPort: 80